### ISSUE TITLE
Fails to compile on Mac OSX 10.8.5

### ISSUE THREAD

**Issue by mattmartini** [chneukirchen/nq#12]
Make fails on osx. (works on ubuntu)

$ uname -a
Darwin varena 12.6.0 Darwin Kernel Version 12.6.0: Wed Mar 18 16:23:48 PDT 2015; root:xnu-2050.48.19~1/RELEASE_X86_64 x86_64

$ cc -v
Apple LLVM version 5.1 (clang-503.0.40) (based on LLVM 3.4svn)
Target: x86_64-apple-darwin12.6.0
Thread model: posix

$ make
cc -g -Wall -O2    nq.c   -o nq
nq.c:175:12: warning: implicit declaration of function 'openat' is invalid in C99
      [-Wimplicit-function-declaration]
                lockfd = openat(dirfd, lockfile, O_RDWR | O_APPEND);
                         ^
nq.c:210:2: warning: implicit declaration of function 'renameat' is invalid in C99
      [-Wimplicit-function-declaration]
        renameat(dirfd, lockfile, dirfd, lockfile+1);
        ^
nq.c:249:9: warning: implicit declaration of function 'fdopendir' is invalid in C99
      [-Wimplicit-function-declaration]
                dir = fdopendir(dirfd);
                      ^
nq.c:249:7: warning: incompatible integer to pointer conversion assigning to 'DIR *' from 'int'
      [-Wint-conversion]
                dir = fdopendir(dirfd);
                    ^ ~~~~~~~~~~~~~~~~
4 warnings generated.
Undefined symbols for architecture x86_64:
  "_fdopendir", referenced from:
      _main in nq-179326.o
  "_openat", referenced from:
      _main in nq-179326.o
  "_renameat", referenced from:
      _main in nq-179326.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [nq] Error 1

**Comment by chneukirchen** [comment]
Yes, you'll need OS X 10.10 for now.

I'm investigating whether backporting this is reasonably easy.

**Comment by antifuchs** [comment]
These functions are defined in gnulib: http://www.gnu.org/software/gnulib/ - but adding this seems to pull in autoconf, which ... um. Sounds like it's not an option.
